import csv
import json

with open('raw_data/law_clusters_edited_v6.csv', encoding='utf8') as f:
    with open('../data/laws/law-clusters.js', 'w') as out_file:
        all_rows = list(csv.DictReader(f))
        out_file.write("// generated by: scripts/law_clusters_to_js.py\n")
        out_file.write(f"const LAWS_IN_CLUSTERS = {json.dumps(all_rows, indent=2, ensure_ascii=False)};")

print("Wrote to data/laws/law-clusters.js")

    